kind: pipeline
type: docker
name: makedeb

steps:
  - name: Build
    image: ubuntu
    volumes:
      - name: Package Directory
        path: /tmp/makedeb/package
    commands:
      # INSTALL NEEDED PACKAGES
      - dpkg-reconfigure debconf -f noninteractive
      - apt update
      - apt dist-upgrade -y
      - apt install wget sudo -y
      # SET UP REPO AND INSTALL MAKEPKG
      - wget 'https://hunterwittenborn.com/keys/apt.asc' -O /etc/apt/trusted.gpg.d/hwittenborn.asc
      - echo 'deb [arch=all] https://repo.hunterwittenborn.com/debian/makedeb any main' | tee /etc/apt/sources.list.d/makedeb.list
      - apt update
      - apt install makepkg -y
      # CREATE BUILD USER
      - useradd -m user
      # SET FOLDER PERMS AND BUILD MAKEDEB
      - chown user:user /drone/
      - chown user:user /drone/src -R
      - ./makedeb.sh --user user

      # TESTING CHECKS
      - apt list dpkg-dev
      - /usr/bin/dpkg-name
