---
kind: pipeline
type: docker
name: Configure PKGBUILDs

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: Clone
  image: docker.hunterwittenborn.com/hwittenborn/drone-git
  settings:
    action: clone
    ssh_key:
      from_secret: kavplex_github_ssh_key
    ssh_known_hosts:
      from_secret: ssh_known_hosts

- name: Set Variables in PKGBUILDs
  image: ubuntu
  commands:
  - cd ${DRONE_REPO_NAME}
  - scripts/pkgbuild_gen.sh

- name: Push Modified PKGBUILDs Back to GitHub
  image: docker.hunterwittenborn.com/hwittenborn/drone-git
  settings:
    action: push
    message: Updated version in PKGBUILDs [CI SKIP]
    ssh_key:
      from_secret: kavplex_github_ssh_key
    ssh_known_hosts:
      from_secret: ssh_known_hosts

image_pull_secrets:
- nexus_repository_docker_login

---
kind: pipeline
type: docker
name: Build and Publish to APT Repository (Stable Release)

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: Clone
  image: docker.hunterwittenborn.com/hwittenborn/drone-git
  settings:
    action: clone
    ssh_key:
      from_secret: kavplex_github_ssh_key
    ssh_known_hosts:
      from_secret: ssh_known_hosts

- name: Build
  image: ubuntu
  commands:
  - cd ${DRONE_REPO_NAME}
  - scripts/build.sh
  environment:
    DEBIAN_FRONTEND: noninteractive
    release_type: stable

- name: Publish
  image: ubuntu
  commands:
  - cd ${DRONE_REPO_NAME}
  - scripts/publish.sh
  environment:
    DEBIAN_FRONTEND: noninteractive
    nexus_repository_password:
      from_secret: nexus_repository_password

image_pull_secrets:
- nexus_repository_docker_login

trigger:
  branch:
  - stable

depends_on:
- Configure PKGBUILDs

---
kind: pipeline
type: docker
name: Build and Publish to APT Repository (Alpha Release)

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: Clone
  image: docker.hunterwittenborn.com/hwittenborn/drone-git
  settings:
    action: clone
    ssh_key:
      from_secret: kavplex_github_ssh_key
    ssh_known_hosts:
      from_secret: ssh_known_hosts

- name: Build
  image: ubuntu
  commands:
  - cd ${DRONE_REPO_NAME}
  - scripts/build.sh
  environment:
    DEBIAN_FRONTEND: noninteractive
    release_type: alpha

- name: Publish
  image: ubuntu
  commands:
  - cd ${DRONE_REPO_NAME}
  - scripts/publish.sh
  environment:
    DEBIAN_FRONTEND: noninteractive
    nexus_repository_password:
      from_secret: nexus_repository_password

image_pull_secrets:
- nexus_repository_docker_login

trigger:
  branch:
  - alpha

depends_on:
- Configure PKGBUILDs

---
kind: pipeline
type: docker
name: Publish to AUR (Stable Release)

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: Pull Git repository from AUR
  image: docker.hunterwittenborn.com/hwittenborn/drone-aur
  settings:
    action: clone
    pkgname: makedeb
    ssh_key:
      from_secret: kavplex_aur_ssh_key
    ssh_known_hosts:
      from_secret: ssh_known_hosts

- name: Replace AUR PKGBUILD with PKGBUILD from GitHub
  image: ubuntu
  commands:
  - cd ${DRONE_REPO_NAME}
  - scripts/aur_pkgbuild_select.sh
  environment:
    release_type: stable

- name: Push Release to AUR
  image: docker.hunterwittenborn.com/hwittenborn/drone-aur
  settings:
    action: push
    pkgname: makedeb
    ssh_key:
      from_secret: kavplex_aur_ssh_key
    ssh_known_hosts:
      from_secret: ssh_known_hosts

image_pull_secrets:
- nexus_repository_docker_login

trigger:
  branch:
  - stable

depends_on:
- Build and Publish to APT Repository (Stable Release)

---
kind: pipeline
type: docker
name: Publish to AUR (Alpha Release)

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: Pull Git repository from AUR
  image: docker.hunterwittenborn.com/hwittenborn/drone-aur
  settings:
    action: clone
    pkgname: makedeb-alpha
    ssh_key:
      from_secret: kavplex_aur_ssh_key
    ssh_known_hosts:
      from_secret: ssh_known_hosts

- name: Replace AUR PKGBUILD with PKGBUILD from GitHub
  image: ubuntu
  commands:
  - cd ${DRONE_REPO_NAME}
  - scripts/aur_pkgbuild_select.sh
  environment:
    release_type: alpha

- name: Push Release to AUR
  image: docker.hunterwittenborn.com/hwittenborn/drone-aur
  settings:
    action: push
    pkgname: makedeb-alpha
    ssh_key:
      from_secret: kavplex_aur_ssh_key
    ssh_known_hosts:
      from_secret: ssh_known_hosts

image_pull_secrets:
- nexus_repository_docker_login

trigger:
  branch:
  - alpha

depends_on:
- Build and Publish to APT Repository (Alpha Release)

...
