---
name: Bug Report
description: Issues with makedeb, packaging, etc.
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        ### Prenote
        Some of the fields in this form will ask for information from your installation of makedeb. You can obtain the needed info with the following command:
        ```sh
        makedeb --version
        ```

        ---

  - type: textarea
    attributes:
      label: Issue
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Installation Source
      options:
        - APT Repository
        - Arch User Repository (AUR)
        - makedeb Package Repository (MPR)
    validations:
      required: true

  - type: input
    attributes:
      label: makedeb Version
    validations:
      required: true

  - type: dropdown
    attributes:
      label: makedeb Release
      options:
        - Stable
        - Beta
        - Alpha
    validations:
      required: true

  - type: input
    attributes:
      label: makepkg Version
    validations:
      required: true
